apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    application: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      application: app1
  template:
    metadata:
      name: app1
      labels:
        application: app1
    spec:
      containers:
      - name: app1
        image: tusharthedockerguy/app:$LATEST
        imagePullPolicy: Always
        ports:
        - containerPort: 8123

