apiVersion: v1
kind: Service
metadata:
  name: app1-service
  labels:
    name: app1-service
    application: app1
spec:
  type: LoadBalancer
  ports:
  - port: 8123
    targetPort: 8123
  selector:
    application: app1
